### ISSUE TITLE
Unable to register user

### ISSUE THREAD

**Issue by Transfusion** [Gate-of-Jade/chinese-resource-app#4]
- Trying to register with a password like `Hunter1234567890@#&*@#` throws a (swallowed) `ValidationError("Password does not have all necessary minimum symbols.")`
https://github.com/Dugong-Chinese/chinese-resource-app/blob/f6003a40accca9b24b42574e1acabd778068affd/api/validators.py#L35
Sample strings that match this regex as generated by `rstr`:
```
>>> import rstr
>>> rstr.xeger(r"!#\$%&\*+,-\./:<;=\?>@\^_\|~")
'!#$%&*************************************,-./:<;=?>@^_|~'
>>> rstr.xeger(r"!#\$%&\*+,-\./:<;=\?>@\^_\|~")
'!#$%&*************************************************************************************************,-./:<;=?>@^_|~'
>>> rstr.xeger(r"!#\$%&\*+,-\./:<;=\?>@\^_\|~")
'!#$%&*********,-./:<;=?>@^_|~'
```
This regex should be fixed to only check for the presence of *at least* one special character in the set; it checks for all of them now. https://regex101.com/

- OR of all the validation conditions does not make sense
https://github.com/Dugong-Chinese/chinese-resource-app/blob/f6003a40accca9b24b42574e1acabd778068affd/api/validators.py#L74-L75
That is to say, if *any* of the criteria is fulfilled, `ValidationError` will be raised. The condition should be `if not all(re.search...`

- Unable to serialize the digest of the hashed password to a string (multiple instances)
```
127.0.0.1 - - [15/Sep/2020 02:47:42] "POST /api/users HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/admin/p/cnr/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/admin/p/cnr/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/admin/p/cnr/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/Users/admin/p/cnr/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/Users/admin/p/cnr/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/Users/admin/p/cnr/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/Users/admin/p/cnr/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/admin/p/cnr/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/admin/p/cnr/lib/python3.8/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/Users/admin/p/cnr/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/admin/p/cnr/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/admin/p/cnr/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/Users/admin/p/cnr/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/Users/admin/p/cnr/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/Users/admin/p/cnr/lib/python3.8/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/Users/admin/p/cnr/lib/python3.8/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/admin/p/cnr/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/admin/p/cnr/lib/python3.8/site-packages/flask/_compat.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/Users/admin/p/cnr/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/admin/p/cnr/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/admin/p/cnr/lib/python3.8/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/admin/p/cnr/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/admin/p/cnr/lib/python3.8/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/admin/p/chinese-resource-app/api/routes.py", line 136, in post
    hashed_password = hash_password(user_password, salt)
  File "/Users/admin/p/chinese-resource-app/api/security.py", line 37, in hash_password
    return str(hasher.digest(), encoding=ENCODING)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc6 in position 0: invalid continuation byte
```
I suggest using `.hexdigest()` instead of `.digest()` throughout and not bothering with `utf-8` encoding, as that is bound to output [0-9][A-F].
https://github.com/Dugong-Chinese/chinese-resource-app/blob/f6003a40accca9b24b42574e1acabd778068affd/api/security.py#L30-L37

**Comment by berzi** [comment]
Most of the correction code is ready and will be pushed to /dev soon, however the `update()` method does not accept arguments in `str` form so the encoding (`utf8_to_bytes`) will stay in place. The output is now a hexdigest and not a reencoded bytes digest as per your suggestion.
